ansible_user: ec2-user
ansible_password: DevOps321
mongodb_host: mongodb-dev.devopswiththota.online
catalogue_host: catalogue-dev.devopswiththota.online
redis_host: redis-dev.devopswiththota.online
mysql_host: mysql-dev.devopswiththota.online
rabbitmq_host: rabbitmq-dev.devopswiththota.online
cart_host: cart-dev.devopswiththota.online
user_host: user-dev.devopswiththota.online
shipping_host: shipping-dev.devopswiththota.online
payment_host: payment-dev.devopswiththota.online