- name: configuring redis server on ec2 instance
  hosts: redis
  become: yes
  tasks:
  - name: enabling redis 7 version
    ansible.builtin.command: dnf module enable redis:7 -y
  - name: installing redis 7 version
    ansible.builtin.dnf:
      name: redis
      state: present
  - name: updating the conf file
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    loop:
    - { regexp: '^bind 127\.0\.0\.1', replace: 'bind 0.0.0.0' }
    - { regexp: '^protected-mode yes', replace: 'protected-mode no' }
  - name: start and enabling the service
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes