- name: app_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml
- name: node_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: node_setup.yaml
- name: updating the .conf files
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: daemon_reload
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: restarting the nginx
  ansible.builtin.service:
    name: nginx
    state: restarted