- name: configuring rabbitmq on ec2 instance
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copying content from rabbitmq.repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo
  - name: installing rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present
  - name: starting and enabling rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes
  - name: adding user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present