- name: configuring mysql server on ec2 instance
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql-server
    ansible.builtin.dnf:
      name: mysql-server
      state: present
  - name: starting and enabling mysqld
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: setting up root passowrd
    ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ ansible_password }}"