- name: installing mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: present
- name: starting and enabling mysqld
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
- name: setting up root passowrd
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD  }}"