- name: Template a file to /etc/file.conf #updating conf file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
- name: daemon_reload
  ansible.builtin.systemd_service:
    daemon_reload: true